/**
 * Conjugation tables for the drill — European Portuguese forms, hand-checked.
 * Note the EP first-person-plural preterite of -ar verbs: -ámos (falámos),
 * unlike Brazilian -amos. Persons: eu, tu, ele/ela, nós, eles/elas (no vós).
 *
 * The imperative uses the same five slots but reads differently:
 * [—, tu, você, nós, vocês] — there is no "eu" imperative, so slot 0 is null.
 */

export type Tense =
  | "presente"
  | "perfeito"
  | "imperfeito"
  | "futuro"
  | "conjuntivo"
  | "imperativo";
export const TENSE_LABEL: Record<Tense, string> = {
  presente: "Presente",
  perfeito: "Pretérito perfeito",
  imperfeito: "Pretérito imperfeito",
  futuro: "Futuro",
  conjuntivo: "Conjuntivo (presente)",
  imperativo: "Imperativo",
};
export const PERSONS = ["eu", "tu", "ele/ela", "nós", "eles/elas"] as const;
/** Imperative slots address different people than the indicative ones. */
export const IMPERATIVE_PERSONS = ["—", "tu", "você", "nós", "vocês"] as const;

/** How to label slot `i` of a given tense in a prompt. */
export function personLabel(tense: Tense, i: number): string {
  return tense === "imperativo" ? IMPERATIVE_PERSONS[i] : PERSONS[i];
}

/** Five slots — a null means "this person has no form" (imperativo eu). */
type Forms = (string | null)[];
export type Verb = {
  inf: string;
  en: string;
  forms: Partial<Record<Tense, Forms>>;
};

export const VERBS: Verb[] = [
  { inf: "ser", en: "to be (permanent)", forms: { presente: ["sou", "és", "é", "somos", "são"], perfeito: ["fui", "foste", "foi", "fomos", "foram"], imperfeito: ["era", "eras", "era", "éramos", "eram"], conjuntivo: ["seja", "sejas", "seja", "sejamos", "sejam"], futuro: ["serei", "serás", "será", "seremos", "serão"], imperativo: [null, "sê", "seja", "sejamos", "sejam"] } },
  { inf: "estar", en: "to be (state)", forms: { presente: ["estou", "estás", "está", "estamos", "estão"], perfeito: ["estive", "estiveste", "esteve", "estivemos", "estiveram"], imperfeito: ["estava", "estavas", "estava", "estávamos", "estavam"], conjuntivo: ["esteja", "estejas", "esteja", "estejamos", "estejam"], futuro: ["estarei", "estarás", "estará", "estaremos", "estarão"], imperativo: [null, "está", "esteja", "estejamos", "estejam"] } },
  { inf: "ter", en: "to have", forms: { presente: ["tenho", "tens", "tem", "temos", "têm"], perfeito: ["tive", "tiveste", "teve", "tivemos", "tiveram"], imperfeito: ["tinha", "tinhas", "tinha", "tínhamos", "tinham"], conjuntivo: ["tenha", "tenhas", "tenha", "tenhamos", "tenham"], futuro: ["terei", "terás", "terá", "teremos", "terão"], imperativo: [null, "tem", "tenha", "tenhamos", "tenham"] } },
  { inf: "ir", en: "to go", forms: { presente: ["vou", "vais", "vai", "vamos", "vão"], perfeito: ["fui", "foste", "foi", "fomos", "foram"], imperfeito: ["ia", "ias", "ia", "íamos", "iam"], conjuntivo: ["vá", "vás", "vá", "vamos", "vão"], futuro: ["irei", "irás", "irá", "iremos", "irão"], imperativo: [null, "vai", "vá", "vamos", "vão"] } },
  { inf: "fazer", en: "to do / make", forms: { presente: ["faço", "fazes", "faz", "fazemos", "fazem"], perfeito: ["fiz", "fizeste", "fez", "fizemos", "fizeram"], imperfeito: ["fazia", "fazias", "fazia", "fazíamos", "faziam"], conjuntivo: ["faça", "faças", "faça", "façamos", "façam"], futuro: ["farei", "farás", "fará", "faremos", "farão"], imperativo: [null, "faz", "faça", "façamos", "façam"] } },
  { inf: "poder", en: "to be able to", forms: { presente: ["posso", "podes", "pode", "podemos", "podem"], perfeito: ["pude", "pudeste", "pôde", "pudemos", "puderam"], imperfeito: ["podia", "podias", "podia", "podíamos", "podiam"], conjuntivo: ["possa", "possas", "possa", "possamos", "possam"], futuro: ["poderei", "poderás", "poderá", "poderemos", "poderão"] } },
  { inf: "querer", en: "to want", forms: { presente: ["quero", "queres", "quer", "queremos", "querem"], perfeito: ["quis", "quiseste", "quis", "quisemos", "quiseram"], imperfeito: ["queria", "querias", "queria", "queríamos", "queriam"], conjuntivo: ["queira", "queiras", "queira", "queiramos", "queiram"], futuro: ["quererei", "quererás", "quererá", "quereremos", "quererão"] } },
  { inf: "dizer", en: "to say", forms: { presente: ["digo", "dizes", "diz", "dizemos", "dizem"], perfeito: ["disse", "disseste", "disse", "dissemos", "disseram"], imperfeito: ["dizia", "dizias", "dizia", "dizíamos", "diziam"], conjuntivo: ["diga", "digas", "diga", "digamos", "digam"], futuro: ["direi", "dirás", "dirá", "diremos", "dirão"], imperativo: [null, "diz", "diga", "digamos", "digam"] } },
  { inf: "ver", en: "to see", forms: { presente: ["vejo", "vês", "vê", "vemos", "veem"], perfeito: ["vi", "viste", "viu", "vimos", "viram"], imperfeito: ["via", "vias", "via", "víamos", "viam"], conjuntivo: ["veja", "vejas", "veja", "vejamos", "vejam"], futuro: ["verei", "verás", "verá", "veremos", "verão"], imperativo: [null, "vê", "veja", "vejamos", "vejam"] } },
  { inf: "vir", en: "to come", forms: { presente: ["venho", "vens", "vem", "vimos", "vêm"], perfeito: ["vim", "vieste", "veio", "viemos", "vieram"], imperfeito: ["vinha", "vinhas", "vinha", "vínhamos", "vinham"], conjuntivo: ["venha", "venhas", "venha", "venhamos", "venham"], futuro: ["virei", "virás", "virá", "viremos", "virão"], imperativo: [null, "vem", "venha", "venhamos", "venham"] } },
  { inf: "dar", en: "to give", forms: { presente: ["dou", "dás", "dá", "damos", "dão"], perfeito: ["dei", "deste", "deu", "demos", "deram"], imperfeito: ["dava", "davas", "dava", "dávamos", "davam"], conjuntivo: ["dê", "dês", "dê", "demos", "deem"], futuro: ["darei", "darás", "dará", "daremos", "darão"], imperativo: [null, "dá", "dê", "demos", "deem"] } },
  { inf: "saber", en: "to know (facts)", forms: { presente: ["sei", "sabes", "sabe", "sabemos", "sabem"], perfeito: ["soube", "soubeste", "soube", "soubemos", "souberam"], imperfeito: ["sabia", "sabias", "sabia", "sabíamos", "sabiam"], conjuntivo: ["saiba", "saibas", "saiba", "saibamos", "saibam"], futuro: ["saberei", "saberás", "saberá", "saberemos", "saberão"], imperativo: [null, "sabe", "saiba", "saibamos", "saibam"] } },
  { inf: "pôr", en: "to put", forms: { presente: ["ponho", "pões", "põe", "pomos", "põem"], perfeito: ["pus", "puseste", "pôs", "pusemos", "puseram"], imperfeito: ["punha", "punhas", "punha", "púnhamos", "punham"], conjuntivo: ["ponha", "ponhas", "ponha", "ponhamos", "ponham"], futuro: ["porei", "porás", "porá", "poremos", "porão"], imperativo: [null, "põe", "ponha", "ponhamos", "ponham"] } },
  { inf: "trazer", en: "to bring", forms: { presente: ["trago", "trazes", "traz", "trazemos", "trazem"], perfeito: ["trouxe", "trouxeste", "trouxe", "trouxemos", "trouxeram"], imperfeito: ["trazia", "trazias", "trazia", "trazíamos", "traziam"], futuro: ["trarei", "trarás", "trará", "traremos", "trarão"], imperativo: [null, "traz", "traga", "tragamos", "tragam"] } },
  { inf: "ler", en: "to read", forms: { presente: ["leio", "lês", "lê", "lemos", "leem"], perfeito: ["li", "leste", "leu", "lemos", "leram"], imperfeito: ["lia", "lias", "lia", "líamos", "liam"], futuro: ["lerei", "lerás", "lerá", "leremos", "lerão"], imperativo: [null, "lê", "leia", "leiamos", "leiam"] } },
  { inf: "ouvir", en: "to hear", forms: { presente: ["ouço", "ouves", "ouve", "ouvimos", "ouvem"], perfeito: ["ouvi", "ouviste", "ouviu", "ouvimos", "ouviram"], imperfeito: ["ouvia", "ouvias", "ouvia", "ouvíamos", "ouviam"], futuro: ["ouvirei", "ouvirás", "ouvirá", "ouviremos", "ouvirão"], imperativo: [null, "ouve", "ouça", "ouçamos", "ouçam"] } },
  { inf: "pedir", en: "to ask for", forms: { presente: ["peço", "pedes", "pede", "pedimos", "pedem"], perfeito: ["pedi", "pediste", "pediu", "pedimos", "pediram"], imperfeito: ["pedia", "pedias", "pedia", "pedíamos", "pediam"], futuro: ["pedirei", "pedirás", "pedirá", "pediremos", "pedirão"], imperativo: [null, "pede", "peça", "peçamos", "peçam"] } },
  { inf: "dormir", en: "to sleep", forms: { presente: ["durmo", "dormes", "dorme", "dormimos", "dormem"], perfeito: ["dormi", "dormiste", "dormiu", "dormimos", "dormiram"], imperfeito: ["dormia", "dormias", "dormia", "dormíamos", "dormiam"], futuro: ["dormirei", "dormirás", "dormirá", "dormiremos", "dormirão"], imperativo: [null, "dorme", "durma", "durmamos", "durmam"] } },
  { inf: "sair", en: "to go out / leave", forms: { presente: ["saio", "sais", "sai", "saímos", "saem"], perfeito: ["saí", "saíste", "saiu", "saímos", "saíram"], imperfeito: ["saía", "saías", "saía", "saíamos", "saíam"], futuro: ["sairei", "sairás", "sairá", "sairemos", "sairão"], imperativo: [null, "sai", "saia", "saiamos", "saiam"] } },
  { inf: "ficar", en: "to stay / become", forms: { presente: ["fico", "ficas", "fica", "ficamos", "ficam"], perfeito: ["fiquei", "ficaste", "ficou", "ficámos", "ficaram"], imperfeito: ["ficava", "ficavas", "ficava", "ficávamos", "ficavam"], futuro: ["ficarei", "ficarás", "ficará", "ficaremos", "ficarão"], imperativo: [null, "fica", "fique", "fiquemos", "fiquem"] } },
  { inf: "começar", en: "to begin", forms: { presente: ["começo", "começas", "começa", "começamos", "começam"], perfeito: ["comecei", "começaste", "começou", "começámos", "começaram"], imperfeito: ["começava", "começavas", "começava", "começávamos", "começavam"], futuro: ["começarei", "começarás", "começará", "começaremos", "começarão"], imperativo: [null, "começa", "comece", "comecemos", "comecem"] } },
  { inf: "chegar", en: "to arrive", forms: { presente: ["chego", "chegas", "chega", "chegamos", "chegam"], perfeito: ["cheguei", "chegaste", "chegou", "chegámos", "chegaram"], imperfeito: ["chegava", "chegavas", "chegava", "chegávamos", "chegavam"], futuro: ["chegarei", "chegarás", "chegará", "chegaremos", "chegarão"], imperativo: [null, "chega", "chegue", "cheguemos", "cheguem"] } },
  { inf: "falar", en: "to speak", forms: { presente: ["falo", "falas", "fala", "falamos", "falam"], perfeito: ["falei", "falaste", "falou", "falámos", "falaram"], imperfeito: ["falava", "falavas", "falava", "falávamos", "falavam"], futuro: ["falarei", "falarás", "falará", "falaremos", "falarão"], imperativo: [null, "fala", "fale", "falemos", "falem"] } },
  { inf: "comer", en: "to eat", forms: { presente: ["como", "comes", "come", "comemos", "comem"], perfeito: ["comi", "comeste", "comeu", "comemos", "comeram"], imperfeito: ["comia", "comias", "comia", "comíamos", "comiam"], futuro: ["comerei", "comerás", "comerá", "comeremos", "comerão"], imperativo: [null, "come", "coma", "comamos", "comam"] } },
  { inf: "abrir", en: "to open", forms: { presente: ["abro", "abres", "abre", "abrimos", "abrem"], perfeito: ["abri", "abriste", "abriu", "abrimos", "abriram"], imperfeito: ["abria", "abrias", "abria", "abríamos", "abriam"], futuro: ["abrirei", "abrirás", "abrirá", "abriremos", "abrirão"], imperativo: [null, "abre", "abra", "abramos", "abram"] } },
  { inf: "gostar", en: "to like", forms: { presente: ["gosto", "gostas", "gosta", "gostamos", "gostam"], perfeito: ["gostei", "gostaste", "gostou", "gostámos", "gostaram"], imperfeito: ["gostava", "gostavas", "gostava", "gostávamos", "gostavam"], futuro: ["gostarei", "gostarás", "gostará", "gostaremos", "gostarão"] } },
  { inf: "precisar", en: "to need", forms: { presente: ["preciso", "precisas", "precisa", "precisamos", "precisam"], perfeito: ["precisei", "precisaste", "precisou", "precisámos", "precisaram"], imperfeito: ["precisava", "precisavas", "precisava", "precisávamos", "precisavam"], futuro: ["precisarei", "precisarás", "precisará", "precisaremos", "precisarão"] } },
  { inf: "conhecer", en: "to know (people/places)", forms: { presente: ["conheço", "conheces", "conhece", "conhecemos", "conhecem"], perfeito: ["conheci", "conheceste", "conheceu", "conhecemos", "conheceram"], imperfeito: ["conhecia", "conhecias", "conhecia", "conhecíamos", "conheciam"], futuro: ["conhecerei", "conhecerás", "conhecerá", "conheceremos", "conhecerão"], imperativo: [null, "conhece", "conheça", "conheçamos", "conheçam"] } },
  { inf: "escrever", en: "to write", forms: { presente: ["escrevo", "escreves", "escreve", "escrevemos", "escrevem"], perfeito: ["escrevi", "escreveste", "escreveu", "escrevemos", "escreveram"], imperfeito: ["escrevia", "escrevias", "escrevia", "escrevíamos", "escreviam"], futuro: ["escreverei", "escreverás", "escreverá", "escreveremos", "escreverão"], imperativo: [null, "escreve", "escreva", "escrevamos", "escrevam"] } },
  { inf: "comprar", en: "to buy", forms: { presente: ["compro", "compras", "compra", "compramos", "compram"], perfeito: ["comprei", "compraste", "comprou", "comprámos", "compraram"], imperfeito: ["comprava", "compravas", "comprava", "comprávamos", "compravam"], futuro: ["comprarei", "comprarás", "comprará", "compraremos", "comprarão"], imperativo: [null, "compra", "compre", "compremos", "comprem"] } },

  // ── Verbos regulares em -ar ────────────────────────────────────────────────
  // Reminder: EP perfeito nós takes the accent (andámos), and -car/-gar/-çar
  // shift spelling in the eu form (brinquei, joguei, almocei).
  { inf: "achar", en: "to think / to find", forms: { presente: ["acho", "achas", "acha", "achamos", "acham"], perfeito: ["achei", "achaste", "achou", "achámos", "acharam"], imperfeito: ["achava", "achavas", "achava", "achávamos", "achavam"], futuro: ["acharei", "acharás", "achará", "acharemos", "acharão"], imperativo: [null, "acha", "ache", "achemos", "achem"] } },
  { inf: "acabar", en: "to finish", forms: { presente: ["acabo", "acabas", "acaba", "acabamos", "acabam"], perfeito: ["acabei", "acabaste", "acabou", "acabámos", "acabaram"], imperfeito: ["acabava", "acabavas", "acabava", "acabávamos", "acabavam"], futuro: ["acabarei", "acabarás", "acabará", "acabaremos", "acabarão"], imperativo: [null, "acaba", "acabe", "acabemos", "acabem"] } },
  { inf: "acordar", en: "to wake up", forms: { presente: ["acordo", "acordas", "acorda", "acordamos", "acordam"], perfeito: ["acordei", "acordaste", "acordou", "acordámos", "acordaram"], imperfeito: ["acordava", "acordavas", "acordava", "acordávamos", "acordavam"], futuro: ["acordarei", "acordarás", "acordará", "acordaremos", "acordarão"], imperativo: [null, "acorda", "acorde", "acordemos", "acordem"] } },
  { inf: "ajudar", en: "to help", forms: { presente: ["ajudo", "ajudas", "ajuda", "ajudamos", "ajudam"], perfeito: ["ajudei", "ajudaste", "ajudou", "ajudámos", "ajudaram"], imperfeito: ["ajudava", "ajudavas", "ajudava", "ajudávamos", "ajudavam"], futuro: ["ajudarei", "ajudarás", "ajudará", "ajudaremos", "ajudarão"], imperativo: [null, "ajuda", "ajude", "ajudemos", "ajudem"] } },
  { inf: "almoçar", en: "to have lunch", forms: { presente: ["almoço", "almoças", "almoça", "almoçamos", "almoçam"], perfeito: ["almocei", "almoçaste", "almoçou", "almoçámos", "almoçaram"], imperfeito: ["almoçava", "almoçavas", "almoçava", "almoçávamos", "almoçavam"], futuro: ["almoçarei", "almoçarás", "almoçará", "almoçaremos", "almoçarão"], imperativo: [null, "almoça", "almoce", "almocemos", "almocem"] } },
  { inf: "andar", en: "to walk / to go about", forms: { presente: ["ando", "andas", "anda", "andamos", "andam"], perfeito: ["andei", "andaste", "andou", "andámos", "andaram"], imperfeito: ["andava", "andavas", "andava", "andávamos", "andavam"], futuro: ["andarei", "andarás", "andará", "andaremos", "andarão"], imperativo: [null, "anda", "ande", "andemos", "andem"] } },
  { inf: "apanhar", en: "to catch / to pick up", forms: { presente: ["apanho", "apanhas", "apanha", "apanhamos", "apanham"], perfeito: ["apanhei", "apanhaste", "apanhou", "apanhámos", "apanharam"], imperfeito: ["apanhava", "apanhavas", "apanhava", "apanhávamos", "apanhavam"], futuro: ["apanharei", "apanharás", "apanhará", "apanharemos", "apanharão"], imperativo: [null, "apanha", "apanhe", "apanhemos", "apanhem"] } },
  { inf: "arranjar", en: "to get / to fix", forms: { presente: ["arranjo", "arranjas", "arranja", "arranjamos", "arranjam"], perfeito: ["arranjei", "arranjaste", "arranjou", "arranjámos", "arranjaram"], imperfeito: ["arranjava", "arranjavas", "arranjava", "arranjávamos", "arranjavam"], futuro: ["arranjarei", "arranjarás", "arranjará", "arranjaremos", "arranjarão"], imperativo: [null, "arranja", "arranje", "arranjemos", "arranjem"] } },
  { inf: "arrumar", en: "to tidy up", forms: { presente: ["arrumo", "arrumas", "arruma", "arrumamos", "arrumam"], perfeito: ["arrumei", "arrumaste", "arrumou", "arrumámos", "arrumaram"], imperfeito: ["arrumava", "arrumavas", "arrumava", "arrumávamos", "arrumavam"], futuro: ["arrumarei", "arrumarás", "arrumará", "arrumaremos", "arrumarão"], imperativo: [null, "arruma", "arrume", "arrumemos", "arrumem"] } },
  { inf: "brincar", en: "to play (children)", forms: { presente: ["brinco", "brincas", "brinca", "brincamos", "brincam"], perfeito: ["brinquei", "brincaste", "brincou", "brincámos", "brincaram"], imperfeito: ["brincava", "brincavas", "brincava", "brincávamos", "brincavam"], futuro: ["brincarei", "brincarás", "brincará", "brincaremos", "brincarão"], imperativo: [null, "brinca", "brinque", "brinquemos", "brinquem"] } },
  { inf: "chamar", en: "to call / to be named", forms: { presente: ["chamo", "chamas", "chama", "chamamos", "chamam"], perfeito: ["chamei", "chamaste", "chamou", "chamámos", "chamaram"], imperfeito: ["chamava", "chamavas", "chamava", "chamávamos", "chamavam"], futuro: ["chamarei", "chamarás", "chamará", "chamaremos", "chamarão"], imperativo: [null, "chama", "chame", "chamemos", "chamem"] } },
  { inf: "contar", en: "to count / to tell", forms: { presente: ["conto", "contas", "conta", "contamos", "contam"], perfeito: ["contei", "contaste", "contou", "contámos", "contaram"], imperfeito: ["contava", "contavas", "contava", "contávamos", "contavam"], futuro: ["contarei", "contarás", "contará", "contaremos", "contarão"], imperativo: [null, "conta", "conte", "contemos", "contem"] } },
  { inf: "cozinhar", en: "to cook", forms: { presente: ["cozinho", "cozinhas", "cozinha", "cozinhamos", "cozinham"], perfeito: ["cozinhei", "cozinhaste", "cozinhou", "cozinhámos", "cozinharam"], imperfeito: ["cozinhava", "cozinhavas", "cozinhava", "cozinhávamos", "cozinhavam"], futuro: ["cozinharei", "cozinharás", "cozinhará", "cozinharemos", "cozinharão"], imperativo: [null, "cozinha", "cozinhe", "cozinhemos", "cozinhem"] } },
  { inf: "deixar", en: "to leave / to let", forms: { presente: ["deixo", "deixas", "deixa", "deixamos", "deixam"], perfeito: ["deixei", "deixaste", "deixou", "deixámos", "deixaram"], imperfeito: ["deixava", "deixavas", "deixava", "deixávamos", "deixavam"], futuro: ["deixarei", "deixarás", "deixará", "deixaremos", "deixarão"], imperativo: [null, "deixa", "deixe", "deixemos", "deixem"] } },
  { inf: "encontrar", en: "to find / to meet", forms: { presente: ["encontro", "encontras", "encontra", "encontramos", "encontram"], perfeito: ["encontrei", "encontraste", "encontrou", "encontrámos", "encontraram"], imperfeito: ["encontrava", "encontravas", "encontrava", "encontrávamos", "encontravam"], futuro: ["encontrarei", "encontrarás", "encontrará", "encontraremos", "encontrarão"], imperativo: [null, "encontra", "encontre", "encontremos", "encontrem"] } },
  { inf: "ensinar", en: "to teach", forms: { presente: ["ensino", "ensinas", "ensina", "ensinamos", "ensinam"], perfeito: ["ensinei", "ensinaste", "ensinou", "ensinámos", "ensinaram"], imperfeito: ["ensinava", "ensinavas", "ensinava", "ensinávamos", "ensinavam"], futuro: ["ensinarei", "ensinarás", "ensinará", "ensinaremos", "ensinarão"], imperativo: [null, "ensina", "ensine", "ensinemos", "ensinem"] } },
  { inf: "entrar", en: "to enter / to come in", forms: { presente: ["entro", "entras", "entra", "entramos", "entram"], perfeito: ["entrei", "entraste", "entrou", "entrámos", "entraram"], imperfeito: ["entrava", "entravas", "entrava", "entrávamos", "entravam"], futuro: ["entrarei", "entrarás", "entrará", "entraremos", "entrarão"], imperativo: [null, "entra", "entre", "entremos", "entrem"] } },
  { inf: "esperar", en: "to wait / to hope", forms: { presente: ["espero", "esperas", "espera", "esperamos", "esperam"], perfeito: ["esperei", "esperaste", "esperou", "esperámos", "esperaram"], imperfeito: ["esperava", "esperavas", "esperava", "esperávamos", "esperavam"], futuro: ["esperarei", "esperarás", "esperará", "esperaremos", "esperarão"], imperativo: [null, "espera", "espere", "esperemos", "esperem"] } },
  { inf: "estudar", en: "to study", forms: { presente: ["estudo", "estudas", "estuda", "estudamos", "estudam"], perfeito: ["estudei", "estudaste", "estudou", "estudámos", "estudaram"], imperfeito: ["estudava", "estudavas", "estudava", "estudávamos", "estudavam"], futuro: ["estudarei", "estudarás", "estudará", "estudaremos", "estudarão"], imperativo: [null, "estuda", "estude", "estudemos", "estudem"] } },
  { inf: "jantar", en: "to have dinner", forms: { presente: ["janto", "jantas", "janta", "jantamos", "jantam"], perfeito: ["jantei", "jantaste", "jantou", "jantámos", "jantaram"], imperfeito: ["jantava", "jantavas", "jantava", "jantávamos", "jantavam"], futuro: ["jantarei", "jantarás", "jantará", "jantaremos", "jantarão"], imperativo: [null, "janta", "jante", "jantemos", "jantem"] } },
  { inf: "jogar", en: "to play (a game)", forms: { presente: ["jogo", "jogas", "joga", "jogamos", "jogam"], perfeito: ["joguei", "jogaste", "jogou", "jogámos", "jogaram"], imperfeito: ["jogava", "jogavas", "jogava", "jogávamos", "jogavam"], futuro: ["jogarei", "jogarás", "jogará", "jogaremos", "jogarão"], imperativo: [null, "joga", "jogue", "joguemos", "joguem"] } },
  { inf: "lavar", en: "to wash", forms: { presente: ["lavo", "lavas", "lava", "lavamos", "lavam"], perfeito: ["lavei", "lavaste", "lavou", "lavámos", "lavaram"], imperfeito: ["lavava", "lavavas", "lavava", "lavávamos", "lavavam"], futuro: ["lavarei", "lavarás", "lavará", "lavaremos", "lavarão"], imperativo: [null, "lava", "lave", "lavemos", "lavem"] } },
  { inf: "lembrar", en: "to remember / to remind", forms: { presente: ["lembro", "lembras", "lembra", "lembramos", "lembram"], perfeito: ["lembrei", "lembraste", "lembrou", "lembrámos", "lembraram"], imperfeito: ["lembrava", "lembravas", "lembrava", "lembrávamos", "lembravam"], futuro: ["lembrarei", "lembrarás", "lembrará", "lembraremos", "lembrarão"], imperativo: [null, "lembra", "lembre", "lembremos", "lembrem"] } },
  { inf: "levantar", en: "to lift / to get up", forms: { presente: ["levanto", "levantas", "levanta", "levantamos", "levantam"], perfeito: ["levantei", "levantaste", "levantou", "levantámos", "levantaram"], imperfeito: ["levantava", "levantavas", "levantava", "levantávamos", "levantavam"], futuro: ["levantarei", "levantarás", "levantará", "levantaremos", "levantarão"], imperativo: [null, "levanta", "levante", "levantemos", "levantem"] } },
  { inf: "levar", en: "to take / to carry", forms: { presente: ["levo", "levas", "leva", "levamos", "levam"], perfeito: ["levei", "levaste", "levou", "levámos", "levaram"], imperfeito: ["levava", "levavas", "levava", "levávamos", "levavam"], futuro: ["levarei", "levarás", "levará", "levaremos", "levarão"], imperativo: [null, "leva", "leve", "levemos", "levem"] } },
  { inf: "ligar", en: "to phone / to switch on", forms: { presente: ["ligo", "ligas", "liga", "ligamos", "ligam"], perfeito: ["liguei", "ligaste", "ligou", "ligámos", "ligaram"], imperfeito: ["ligava", "ligavas", "ligava", "ligávamos", "ligavam"], futuro: ["ligarei", "ligarás", "ligará", "ligaremos", "ligarão"], imperativo: [null, "liga", "ligue", "liguemos", "liguem"] } },
  { inf: "limpar", en: "to clean", forms: { presente: ["limpo", "limpas", "limpa", "limpamos", "limpam"], perfeito: ["limpei", "limpaste", "limpou", "limpámos", "limparam"], imperfeito: ["limpava", "limpavas", "limpava", "limpávamos", "limpavam"], futuro: ["limparei", "limparás", "limpará", "limparemos", "limparão"], imperativo: [null, "limpa", "limpe", "limpemos", "limpem"] } },
  { inf: "morar", en: "to live (reside)", forms: { presente: ["moro", "moras", "mora", "moramos", "moram"], perfeito: ["morei", "moraste", "morou", "morámos", "moraram"], imperfeito: ["morava", "moravas", "morava", "morávamos", "moravam"], futuro: ["morarei", "morarás", "morará", "moraremos", "morarão"], imperativo: [null, "mora", "more", "moremos", "morem"] } },
  { inf: "mostrar", en: "to show", forms: { presente: ["mostro", "mostras", "mostra", "mostramos", "mostram"], perfeito: ["mostrei", "mostraste", "mostrou", "mostrámos", "mostraram"], imperfeito: ["mostrava", "mostravas", "mostrava", "mostrávamos", "mostravam"], futuro: ["mostrarei", "mostrarás", "mostrará", "mostraremos", "mostrarão"], imperativo: [null, "mostra", "mostre", "mostremos", "mostrem"] } },
  { inf: "pagar", en: "to pay", forms: { presente: ["pago", "pagas", "paga", "pagamos", "pagam"], perfeito: ["paguei", "pagaste", "pagou", "pagámos", "pagaram"], imperfeito: ["pagava", "pagavas", "pagava", "pagávamos", "pagavam"], futuro: ["pagarei", "pagarás", "pagará", "pagaremos", "pagarão"], imperativo: [null, "paga", "pague", "paguemos", "paguem"] } },
  { inf: "passar", en: "to pass / to spend (time)", forms: { presente: ["passo", "passas", "passa", "passamos", "passam"], perfeito: ["passei", "passaste", "passou", "passámos", "passaram"], imperfeito: ["passava", "passavas", "passava", "passávamos", "passavam"], futuro: ["passarei", "passarás", "passará", "passaremos", "passarão"], imperativo: [null, "passa", "passe", "passemos", "passem"] } },
  { inf: "pensar", en: "to think", forms: { presente: ["penso", "pensas", "pensa", "pensamos", "pensam"], perfeito: ["pensei", "pensaste", "pensou", "pensámos", "pensaram"], imperfeito: ["pensava", "pensavas", "pensava", "pensávamos", "pensavam"], futuro: ["pensarei", "pensarás", "pensará", "pensaremos", "pensarão"], imperativo: [null, "pensa", "pense", "pensemos", "pensem"] } },
  { inf: "perguntar", en: "to ask", forms: { presente: ["pergunto", "perguntas", "pergunta", "perguntamos", "perguntam"], perfeito: ["perguntei", "perguntaste", "perguntou", "perguntámos", "perguntaram"], imperfeito: ["perguntava", "perguntavas", "perguntava", "perguntávamos", "perguntavam"], futuro: ["perguntarei", "perguntarás", "perguntará", "perguntaremos", "perguntarão"], imperativo: [null, "pergunta", "pergunte", "perguntemos", "perguntem"] } },
  { inf: "procurar", en: "to look for", forms: { presente: ["procuro", "procuras", "procura", "procuramos", "procuram"], perfeito: ["procurei", "procuraste", "procurou", "procurámos", "procuraram"], imperfeito: ["procurava", "procuravas", "procurava", "procurávamos", "procuravam"], futuro: ["procurarei", "procurarás", "procurará", "procuraremos", "procurarão"], imperativo: [null, "procura", "procure", "procuremos", "procurem"] } },
  { inf: "tirar", en: "to take out / to take (a photo)", forms: { presente: ["tiro", "tiras", "tira", "tiramos", "tiram"], perfeito: ["tirei", "tiraste", "tirou", "tirámos", "tiraram"], imperfeito: ["tirava", "tiravas", "tirava", "tirávamos", "tiravam"], futuro: ["tirarei", "tirarás", "tirará", "tiraremos", "tirarão"], imperativo: [null, "tira", "tire", "tiremos", "tirem"] } },
  { inf: "tomar", en: "to take / to drink", forms: { presente: ["tomo", "tomas", "toma", "tomamos", "tomam"], perfeito: ["tomei", "tomaste", "tomou", "tomámos", "tomaram"], imperfeito: ["tomava", "tomavas", "tomava", "tomávamos", "tomavam"], futuro: ["tomarei", "tomarás", "tomará", "tomaremos", "tomarão"], imperativo: [null, "toma", "tome", "tomemos", "tomem"] } },
  { inf: "trabalhar", en: "to work", forms: { presente: ["trabalho", "trabalhas", "trabalha", "trabalhamos", "trabalham"], perfeito: ["trabalhei", "trabalhaste", "trabalhou", "trabalhámos", "trabalharam"], imperfeito: ["trabalhava", "trabalhavas", "trabalhava", "trabalhávamos", "trabalhavam"], futuro: ["trabalharei", "trabalharás", "trabalhará", "trabalharemos", "trabalharão"], imperativo: [null, "trabalha", "trabalhe", "trabalhemos", "trabalhem"] } },
  { inf: "usar", en: "to use / to wear", forms: { presente: ["uso", "usas", "usa", "usamos", "usam"], perfeito: ["usei", "usaste", "usou", "usámos", "usaram"], imperfeito: ["usava", "usavas", "usava", "usávamos", "usavam"], futuro: ["usarei", "usarás", "usará", "usaremos", "usarão"], imperativo: [null, "usa", "use", "usemos", "usem"] } },
  { inf: "voltar", en: "to return / to come back", forms: { presente: ["volto", "voltas", "volta", "voltamos", "voltam"], perfeito: ["voltei", "voltaste", "voltou", "voltámos", "voltaram"], imperfeito: ["voltava", "voltavas", "voltava", "voltávamos", "voltavam"], futuro: ["voltarei", "voltarás", "voltará", "voltaremos", "voltarão"], imperativo: [null, "volta", "volte", "voltemos", "voltem"] } },

  // ── Verbos em -er ─────────────────────────────────────────────────────────
  // No accent on the perfeito nós here: comemos, bebemos, vendemos.
  { inf: "aprender", en: "to learn", forms: { presente: ["aprendo", "aprendes", "aprende", "aprendemos", "aprendem"], perfeito: ["aprendi", "aprendeste", "aprendeu", "aprendemos", "aprenderam"], imperfeito: ["aprendia", "aprendias", "aprendia", "aprendíamos", "aprendiam"], futuro: ["aprenderei", "aprenderás", "aprenderá", "aprenderemos", "aprenderão"], imperativo: [null, "aprende", "aprenda", "aprendamos", "aprendam"] } },
  { inf: "beber", en: "to drink", forms: { presente: ["bebo", "bebes", "bebe", "bebemos", "bebem"], perfeito: ["bebi", "bebeste", "bebeu", "bebemos", "beberam"], imperfeito: ["bebia", "bebias", "bebia", "bebíamos", "bebiam"], futuro: ["beberei", "beberás", "beberá", "beberemos", "beberão"], imperativo: [null, "bebe", "beba", "bebamos", "bebam"] } },
  { inf: "caber", en: "to fit", forms: { presente: ["caibo", "cabes", "cabe", "cabemos", "cabem"], perfeito: ["coube", "coubeste", "coube", "coubemos", "couberam"], imperfeito: ["cabia", "cabias", "cabia", "cabíamos", "cabiam"], futuro: ["caberei", "caberás", "caberá", "caberemos", "caberão"] } },
  { inf: "correr", en: "to run", forms: { presente: ["corro", "corres", "corre", "corremos", "correm"], perfeito: ["corri", "correste", "correu", "corremos", "correram"], imperfeito: ["corria", "corrias", "corria", "corríamos", "corriam"], futuro: ["correrei", "correrás", "correrá", "correremos", "correrão"], imperativo: [null, "corre", "corra", "corramos", "corram"] } },
  { inf: "crescer", en: "to grow", forms: { presente: ["cresço", "cresces", "cresce", "crescemos", "crescem"], perfeito: ["cresci", "cresceste", "cresceu", "crescemos", "cresceram"], imperfeito: ["crescia", "crescias", "crescia", "crescíamos", "cresciam"], futuro: ["crescerei", "crescerás", "crescerá", "cresceremos", "crescerão"], imperativo: [null, "cresce", "cresça", "cresçamos", "cresçam"] } },
  { inf: "descer", en: "to go down", forms: { presente: ["desço", "desces", "desce", "descemos", "descem"], perfeito: ["desci", "desceste", "desceu", "descemos", "desceram"], imperfeito: ["descia", "descias", "descia", "descíamos", "desciam"], futuro: ["descerei", "descerás", "descerá", "desceremos", "descerão"], imperativo: [null, "desce", "desça", "desçamos", "desçam"] } },
  { inf: "dever", en: "to owe / must", forms: { presente: ["devo", "deves", "deve", "devemos", "devem"], perfeito: ["devi", "deveste", "deveu", "devemos", "deveram"], imperfeito: ["devia", "devias", "devia", "devíamos", "deviam"], futuro: ["deverei", "deverás", "deverá", "deveremos", "deverão"] } },
  { inf: "entender", en: "to understand", forms: { presente: ["entendo", "entendes", "entende", "entendemos", "entendem"], perfeito: ["entendi", "entendeste", "entendeu", "entendemos", "entenderam"], imperfeito: ["entendia", "entendias", "entendia", "entendíamos", "entendiam"], futuro: ["entenderei", "entenderás", "entenderá", "entenderemos", "entenderão"], imperativo: [null, "entende", "entenda", "entendamos", "entendam"] } },
  { inf: "escolher", en: "to choose", forms: { presente: ["escolho", "escolhes", "escolhe", "escolhemos", "escolhem"], perfeito: ["escolhi", "escolheste", "escolheu", "escolhemos", "escolheram"], imperfeito: ["escolhia", "escolhias", "escolhia", "escolhíamos", "escolhiam"], futuro: ["escolherei", "escolherás", "escolherá", "escolheremos", "escolherão"], imperativo: [null, "escolhe", "escolha", "escolhamos", "escolham"] } },
  { inf: "esquecer", en: "to forget", forms: { presente: ["esqueço", "esqueces", "esquece", "esquecemos", "esquecem"], perfeito: ["esqueci", "esqueceste", "esqueceu", "esquecemos", "esqueceram"], imperfeito: ["esquecia", "esquecias", "esquecia", "esquecíamos", "esqueciam"], futuro: ["esquecerei", "esquecerás", "esquecerá", "esqueceremos", "esquecerão"], imperativo: [null, "esquece", "esqueça", "esqueçamos", "esqueçam"] } },
  { inf: "haver", en: "there to be / to have to", forms: { presente: ["hei", "hás", "há", "havemos", "hão"], perfeito: ["houve", "houveste", "houve", "houvemos", "houveram"], imperfeito: ["havia", "havias", "havia", "havíamos", "haviam"], futuro: ["haverei", "haverás", "haverá", "haveremos", "haverão"] } },
  { inf: "nascer", en: "to be born", forms: { presente: ["nasço", "nasces", "nasce", "nascemos", "nascem"], perfeito: ["nasci", "nasceste", "nasceu", "nascemos", "nasceram"], imperfeito: ["nascia", "nascias", "nascia", "nascíamos", "nasciam"], futuro: ["nascerei", "nascerás", "nascerá", "nasceremos", "nascerão"] } },
  { inf: "parecer", en: "to seem / to look", forms: { presente: ["pareço", "pareces", "parece", "parecemos", "parecem"], perfeito: ["pareci", "pareceste", "pareceu", "parecemos", "pareceram"], imperfeito: ["parecia", "parecias", "parecia", "parecíamos", "pareciam"], futuro: ["parecerei", "parecerás", "parecerá", "pareceremos", "parecerão"] } },
  { inf: "perceber", en: "to understand", forms: { presente: ["percebo", "percebes", "percebe", "percebemos", "percebem"], perfeito: ["percebi", "percebeste", "percebeu", "percebemos", "perceberam"], imperfeito: ["percebia", "percebias", "percebia", "percebíamos", "percebiam"], futuro: ["perceberei", "perceberás", "perceberá", "perceberemos", "perceberão"], imperativo: [null, "percebe", "perceba", "percebamos", "percebam"] } },
  { inf: "perder", en: "to lose / to miss", forms: { presente: ["perco", "perdes", "perde", "perdemos", "perdem"], perfeito: ["perdi", "perdeste", "perdeu", "perdemos", "perderam"], imperfeito: ["perdia", "perdias", "perdia", "perdíamos", "perdiam"], futuro: ["perderei", "perderás", "perderá", "perderemos", "perderão"], imperativo: [null, "perde", "perca", "percamos", "percam"] } },
  { inf: "receber", en: "to receive", forms: { presente: ["recebo", "recebes", "recebe", "recebemos", "recebem"], perfeito: ["recebi", "recebeste", "recebeu", "recebemos", "receberam"], imperfeito: ["recebia", "recebias", "recebia", "recebíamos", "recebiam"], futuro: ["receberei", "receberás", "receberá", "receberemos", "receberão"], imperativo: [null, "recebe", "receba", "recebamos", "recebam"] } },
  { inf: "responder", en: "to answer", forms: { presente: ["respondo", "respondes", "responde", "respondemos", "respondem"], perfeito: ["respondi", "respondeste", "respondeu", "respondemos", "responderam"], imperfeito: ["respondia", "respondias", "respondia", "respondíamos", "respondiam"], futuro: ["responderei", "responderás", "responderá", "responderemos", "responderão"], imperativo: [null, "responde", "responda", "respondamos", "respondam"] } },
  { inf: "valer", en: "to be worth", forms: { presente: ["valho", "vales", "vale", "valemos", "valem"], perfeito: ["vali", "valeste", "valeu", "valemos", "valeram"], imperfeito: ["valia", "valias", "valia", "valíamos", "valiam"], futuro: ["valerei", "valerás", "valerá", "valeremos", "valerão"] } },
  { inf: "vender", en: "to sell", forms: { presente: ["vendo", "vendes", "vende", "vendemos", "vendem"], perfeito: ["vendi", "vendeste", "vendeu", "vendemos", "venderam"], imperfeito: ["vendia", "vendias", "vendia", "vendíamos", "vendiam"], futuro: ["venderei", "venderás", "venderá", "venderemos", "venderão"], imperativo: [null, "vende", "venda", "vendamos", "vendam"] } },
  { inf: "viver", en: "to live", forms: { presente: ["vivo", "vives", "vive", "vivemos", "vivem"], perfeito: ["vivi", "viveste", "viveu", "vivemos", "viveram"], imperfeito: ["vivia", "vivias", "vivia", "vivíamos", "viviam"], futuro: ["viverei", "viverás", "viverá", "viveremos", "viverão"], imperativo: [null, "vive", "viva", "vivamos", "vivam"] } },

  // ── Verbos em -ir ─────────────────────────────────────────────────────────
  // Watch the vowel changes: subo/sobes, sigo/segues, sinto/sentes, visto/vestes.
  { inf: "assistir", en: "to watch / to attend", forms: { presente: ["assisto", "assistes", "assiste", "assistimos", "assistem"], perfeito: ["assisti", "assististe", "assistiu", "assistimos", "assistiram"], imperfeito: ["assistia", "assistias", "assistia", "assistíamos", "assistiam"], futuro: ["assistirei", "assistirás", "assistirá", "assistiremos", "assistirão"], imperativo: [null, "assiste", "assista", "assistamos", "assistam"] } },
  { inf: "cair", en: "to fall", forms: { presente: ["caio", "cais", "cai", "caímos", "caem"], perfeito: ["caí", "caíste", "caiu", "caímos", "caíram"], imperfeito: ["caía", "caías", "caía", "caíamos", "caíam"], futuro: ["cairei", "cairás", "cairá", "cairemos", "cairão"], imperativo: [null, "cai", "caia", "caiamos", "caiam"] } },
  { inf: "conduzir", en: "to drive", forms: { presente: ["conduzo", "conduzes", "conduz", "conduzimos", "conduzem"], perfeito: ["conduzi", "conduziste", "conduziu", "conduzimos", "conduziram"], imperfeito: ["conduzia", "conduzias", "conduzia", "conduzíamos", "conduziam"], futuro: ["conduzirei", "conduzirás", "conduzirá", "conduziremos", "conduzirão"], imperativo: [null, "conduz", "conduza", "conduzamos", "conduzam"] } },
  { inf: "conseguir", en: "to manage / to be able", forms: { presente: ["consigo", "consegues", "consegue", "conseguimos", "conseguem"], perfeito: ["consegui", "conseguiste", "conseguiu", "conseguimos", "conseguiram"], imperfeito: ["conseguia", "conseguias", "conseguia", "conseguíamos", "conseguiam"], futuro: ["conseguirei", "conseguirás", "conseguirá", "conseguiremos", "conseguirão"], imperativo: [null, "consegue", "consiga", "consigamos", "consigam"] } },
  { inf: "construir", en: "to build", forms: { presente: ["construo", "constróis", "constrói", "construímos", "constroem"], perfeito: ["construí", "construíste", "construiu", "construímos", "construíram"], imperfeito: ["construía", "construías", "construía", "construíamos", "construíam"], futuro: ["construirei", "construirás", "construirá", "construiremos", "construirão"], imperativo: [null, "constrói", "construa", "construamos", "construam"] } },
  { inf: "decidir", en: "to decide", forms: { presente: ["decido", "decides", "decide", "decidimos", "decidem"], perfeito: ["decidi", "decidiste", "decidiu", "decidimos", "decidiram"], imperfeito: ["decidia", "decidias", "decidia", "decidíamos", "decidiam"], futuro: ["decidirei", "decidirás", "decidirá", "decidiremos", "decidirão"], imperativo: [null, "decide", "decida", "decidamos", "decidam"] } },
  { inf: "divertir", en: "to amuse (divertir-se: to have fun)", forms: { presente: ["divirto", "divertes", "diverte", "divertimos", "divertem"], perfeito: ["diverti", "divertiste", "divertiu", "divertimos", "divertiram"], imperfeito: ["divertia", "divertias", "divertia", "divertíamos", "divertiam"], futuro: ["divertirei", "divertirás", "divertirá", "divertiremos", "divertirão"], imperativo: [null, "diverte", "divirta", "divirtamos", "divirtam"] } },
  { inf: "fugir", en: "to run away", forms: { presente: ["fujo", "foges", "foge", "fugimos", "fogem"], perfeito: ["fugi", "fugiste", "fugiu", "fugimos", "fugiram"], imperfeito: ["fugia", "fugias", "fugia", "fugíamos", "fugiam"], futuro: ["fugirei", "fugirás", "fugirá", "fugiremos", "fugirão"], imperativo: [null, "foge", "fuja", "fujamos", "fujam"] } },
  { inf: "incluir", en: "to include", forms: { presente: ["incluo", "incluis", "inclui", "incluímos", "incluem"], perfeito: ["incluí", "incluíste", "incluiu", "incluímos", "incluíram"], imperfeito: ["incluía", "incluías", "incluía", "incluíamos", "incluíam"], futuro: ["incluirei", "incluirás", "incluirá", "incluiremos", "incluirão"] } },
  { inf: "partir", en: "to leave / to break", forms: { presente: ["parto", "partes", "parte", "partimos", "partem"], perfeito: ["parti", "partiste", "partiu", "partimos", "partiram"], imperfeito: ["partia", "partias", "partia", "partíamos", "partiam"], futuro: ["partirei", "partirás", "partirá", "partiremos", "partirão"], imperativo: [null, "parte", "parta", "partamos", "partam"] } },
  { inf: "preferir", en: "to prefer", forms: { presente: ["prefiro", "preferes", "prefere", "preferimos", "preferem"], perfeito: ["preferi", "preferiste", "preferiu", "preferimos", "preferiram"], imperfeito: ["preferia", "preferias", "preferia", "preferíamos", "preferiam"], futuro: ["preferirei", "preferirás", "preferirá", "preferiremos", "preferirão"], imperativo: [null, "prefere", "prefira", "prefiramos", "prefiram"] } },
  { inf: "repetir", en: "to repeat", forms: { presente: ["repito", "repetes", "repete", "repetimos", "repetem"], perfeito: ["repeti", "repetiste", "repetiu", "repetimos", "repetiram"], imperfeito: ["repetia", "repetias", "repetia", "repetíamos", "repetiam"], futuro: ["repetirei", "repetirás", "repetirá", "repetiremos", "repetirão"], imperativo: [null, "repete", "repita", "repitamos", "repitam"] } },
  { inf: "rir", en: "to laugh", forms: { presente: ["rio", "ris", "ri", "rimos", "riem"], perfeito: ["ri", "riste", "riu", "rimos", "riram"], imperfeito: ["ria", "rias", "ria", "ríamos", "riam"], futuro: ["rirei", "rirás", "rirá", "riremos", "rirão"], imperativo: [null, "ri", "ria", "riamos", "riam"] } },
  { inf: "seguir", en: "to follow / to carry on", forms: { presente: ["sigo", "segues", "segue", "seguimos", "seguem"], perfeito: ["segui", "seguiste", "seguiu", "seguimos", "seguiram"], imperfeito: ["seguia", "seguias", "seguia", "seguíamos", "seguiam"], futuro: ["seguirei", "seguirás", "seguirá", "seguiremos", "seguirão"], imperativo: [null, "segue", "siga", "sigamos", "sigam"] } },
  { inf: "sentir", en: "to feel", forms: { presente: ["sinto", "sentes", "sente", "sentimos", "sentem"], perfeito: ["senti", "sentiste", "sentiu", "sentimos", "sentiram"], imperfeito: ["sentia", "sentias", "sentia", "sentíamos", "sentiam"], futuro: ["sentirei", "sentirás", "sentirá", "sentiremos", "sentirão"], imperativo: [null, "sente", "sinta", "sintamos", "sintam"] } },
  { inf: "servir", en: "to serve", forms: { presente: ["sirvo", "serves", "serve", "servimos", "servem"], perfeito: ["servi", "serviste", "serviu", "servimos", "serviram"], imperfeito: ["servia", "servias", "servia", "servíamos", "serviam"], futuro: ["servirei", "servirás", "servirá", "serviremos", "servirão"], imperativo: [null, "serve", "sirva", "sirvamos", "sirvam"] } },
  { inf: "subir", en: "to go up", forms: { presente: ["subo", "sobes", "sobe", "subimos", "sobem"], perfeito: ["subi", "subiste", "subiu", "subimos", "subiram"], imperfeito: ["subia", "subias", "subia", "subíamos", "subiam"], futuro: ["subirei", "subirás", "subirá", "subiremos", "subirão"], imperativo: [null, "sobe", "suba", "subamos", "subam"] } },
  { inf: "vestir", en: "to wear / to dress", forms: { presente: ["visto", "vestes", "veste", "vestimos", "vestem"], perfeito: ["vesti", "vestiste", "vestiu", "vestimos", "vestiram"], imperfeito: ["vestia", "vestias", "vestia", "vestíamos", "vestiam"], futuro: ["vestirei", "vestirás", "vestirá", "vestiremos", "vestirão"], imperativo: [null, "veste", "vista", "vistamos", "vistam"] } },
];

export function verbsWithTense(tenses: Tense[]): Verb[] {
  return VERBS.filter((v) => tenses.some((t) => v.forms[t]));
}
